name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Chỉ cài đặt dependencies mà không nâng cấp
    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    # Cài đặt Postman CLI trên Windows
    - name: Install Postman CLI
      shell: powershell
      run: |
        [System.Net.ServicePointManager]::SecurityProtocol = 3072
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))

    - name: Kiểm tra cài đặt Postman CLI
      run: postman --version

    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    - name: Run API tests
      run: |
        postman collection run "32506681-dadd0737-d711-4ac2-90f8-caeafb2cd4a6" `
        -e "32506681-7b3abf58-1d81-45f5-b05e-443d5c78ba33"
